// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	ftpconnection "github.com/alexZaicev/go-ftp-client/internal/adapters/ftpconnection"
	mock "github.com/stretchr/testify/mock"
)

// DialOption is an autogenerated mock type for the DialOption type
type DialOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: options
func (_m *DialOption) Execute(options *ftpconnection.DialOptions) error {
	ret := _m.Called(options)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ftpconnection.DialOptions) error); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDialOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewDialOption creates a new instance of DialOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDialOption(t mockConstructorTestingTNewDialOption) *DialOption {
	mock := &DialOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
