name: golint
on: [push, pull_request]
jobs:
  checks:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18
      - name: Run tests
        run: make golint