name: golint
on: [push, pull_request]

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-20.04
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    steps:
      - uses: actions/checkout@v3.0.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          only-new-issues: true