name: Units Tests
on: [push]
jobs:
  checks:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18
      - name: Run tests
        run: make unit
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.3
        with:
          github-token: ${{ secrets.coveralls_token }}
          path-to-lcov: coverage.lcov
