name: Units Tests
on: [push, pull_request]
jobs:
  checks:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18
      - name: Run tests
        run: make unit
#      - name: Convert coverage to lcov
#        uses: jandelgado/gcov2lcov-action@c680c0f7c7442485f1749eb2a13e54a686e76eb5
#      - name: Coveralls
#        uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
#        with:
#          github-token: ${{ secrets.github_token }}
#          path-to-lcov: coverage.lcov